In [16]:
import pandas as pd
from pathlib import Path

In [17]:
base_folder = Path.cwd()
print(base_folder)

C:\Users\MAYA\Desktop\data  analysis\final project

In [18]:
feed_folders = list(base_folder.glob("Feed_20*"))

csv_files = []

for folder in feed_folders:
    if folder.is_dir():
        csv_files.extend(folder.rglob("*.csv"))

print("Total CSV files found:", len(csv_files))

for file in csv_files:
    print(file.name)

Total CSV files found: 12
claims_header_2026_01.csv
claim_lines_2026_01.csv
premiums_2026_01.csv
premiums_2026_01-checkpoint.csv
claims_header_2026_02.csv
claim_lines_2026_02.csv
premiums_2026_02.csv
claim_lines_2026_02-checkpoint.csv
claims_header_2026_03.csv
claim_lines_2026_03.csv
premiums_2026_03.csv
claim_lines_2026_03-checkpoint.csv

In [19]:
data = {}

for file in csv_files:
    df = pd.read_csv(file)
    data[file.name] = df

print("Total files loaded:", len(data))

Total files loaded: 12

In [20]:
for name, df in data.items():

    print("\nFile:", name)
    print("Rows and columns:", df.shape)

    print("\nFirst 5 rows:")
    display(df.head())

    print("\nColumn names:")
    print(df.columns.tolist())

    print("\nData types:")
    print(df.dtypes)

    print("\nMissing values:")
    print(df.isnull().sum()[df.isnull().sum() > 0])

    print("\nDuplicate rows:", df.duplicated().sum())

File: claims_header_2026_01.csv
Rows and columns: (6404, 19)

First 5 rows:

,claim_id,member_id,provider_id,claim_type,place_of_service,service_from_date,service_to_date,received_date,processed_date,primary_diagnosis,secondary_diagnosis,total_billed,total_allowed,total_paid,member_responsibility,claim_status,denial_code,submission_channel,original_claim_id
0,CLM1070278,M105444,P2070,Professional,11 - Office,2025-04-08,2025-04-08,2025-10-19,2026-01-24,S83.511A,NaN,734.18,0.00,0.00,0.00,Denied,TF01,Paper,NaN
1,CLM1009377,M100747,P2058,Professional,11 - Office,2025-08-14,2025-08-14,2025-10-20,2026-01-01,R10.9,NaN,477.47,273.86,191.71,82.15,Paid,NaN,Paper,NaN
2,CLM1001951,M100172,P2150,Professional,11 - Office,2025-10-27,2025-10-27,2025-10-31,2026-01-07,G43.909,NaN,573.78,392.08,352.88,39.20,Paid,NaN,Paper,NaN
3,CLM1087922,M106832,P2043,Institutional,23 - Emergency Room,2025-10-24,2025-10-24,2025-11-03,2026-01-25,R10.9,NaN,3860.38,2007.32,1605.87,401.46,Paid,NaN,Paper,NaN
4,CLM1097126,M107552,P2027,Professional,11 - Office,2025-10-02,2025-10-02,2025-11-03,2026-01-01,D48.5,NaN,1102.44,449.81,382.34,67.47,Paid,NaN,Paper,NaN

Column names:
['claim_id', 'member_id', 'provider_id', 'claim_type', 'place_of_service', 'service_from_date', 'service_to_date', 'received_date', 'processed_date', 'primary_diagnosis', 'secondary_diagnosis', 'total_billed', 'total_allowed', 'total_paid', 'member_responsibility', 'claim_status', 'denial_code', 'submission_channel', 'original_claim_id']

Data types:
claim_id                  object
member_id                 object
provider_id               object
claim_type                object
place_of_service          object
service_from_date         object
service_to_date           object
received_date             object
processed_date            object
primary_diagnosis         object
secondary_diagnosis       object
total_billed             float64
total_allowed            float64
total_paid               float64
member_responsibility    float64
claim_status              object
denial_code               object
submission_channel        object
original_claim_id         object
dtype: object

Missing values:
processed_date         1061
secondary_diagnosis    5609
denial_code            6021
original_claim_id      6362
dtype: int64

Duplicate rows: 0

File: claim_lines_2026_01.csv
Rows and columns: (12914, 9)

First 5 rows:

,claim_id,line_number,procedure_code,modifier,units,billed_amount,allowed_amount,paid_amount,line_status
0,CLM1000013,1,99213,NaN,1,514.87,281.12,253.00,Paid
1,CLM1000013,2,80061,NaN,1,72.12,49.52,44.57,Paid
2,CLM1000028,1,97110,GP,4,603.53,338.10,304.28,Paid
3,CLM1000028,2,97140,GP,1,141.81,76.41,68.77,Paid
4,CLM1000043,1,90834,NaN,1,596.75,325.34,292.80,Paid

Column names:
['claim_id', 'line_number', 'procedure_code', 'modifier', 'units', 'billed_amount', 'allowed_amount', 'paid_amount', 'line_status']

Data types:
claim_id           object
line_number         int64
procedure_code     object
modifier           object
units               int64
billed_amount     float64
allowed_amount    float64
paid_amount       float64
line_status        object
dtype: object

Missing values:
modifier    11936
dtype: int64

Duplicate rows: 0

File: premiums_2026_01.csv
Rows and columns: (6928, 5)

First 5 rows:

  member_id premium_month plan_id  premium_amount payment_status
0   M100001       2026-01   PLN03             420       Received
1   M100002       2026-01   PLN08             370       Received
2   M100003       2026-01   PLN06             720       Received
3   M100004       2026-01   PLN07             960       Received
4   M100006       2026-01   PLN02             400       Received

Column names:
['member_id', 'premium_month', 'plan_id', 'premium_amount', 'payment_status']

Data types:
member_id         object
premium_month     object
plan_id           object
premium_amount     int64
payment_status    object
dtype: object

Missing values:
Series([], dtype: int64)

Duplicate rows: 0

File: premiums_2026_01-checkpoint.csv
Rows and columns: (6928, 5)

First 5 rows:

  member_id premium_month plan_id  premium_amount payment_status
0   M100001       2026-01   PLN03             420       Received
1   M100002       2026-01   PLN08             370       Received
2   M100003       2026-01   PLN06             720       Received
3   M100004       2026-01   PLN07             960       Received
4   M100006       2026-01   PLN02             400       Received

Column names:
['member_id', 'premium_month', 'plan_id', 'premium_amount', 'payment_status']

Data types:
member_id         object
premium_month     object
plan_id           object
premium_amount     int64
payment_status    object
dtype: object

Missing values:
Series([], dtype: int64)

Duplicate rows: 0

File: claims_header_2026_02.csv
Rows and columns: (5266, 19)

First 5 rows:

,claim_id,mbr_id,provider_id,claim_type,place_of_service,svc_from_dt,svc_to_dt,received_date,processed_date,primary_diagnosis,secondary_diagnosis,total_billed,allowed_amt,paid_amt,member_responsibility,claim_status,denial_code,submission_channel,original_claim_id
0,CLM1013201,M101034,P2148,Professional,11 - Office,01-12-2025,01-12-2025,01-01-2026,22-02-2026,J10.1,NaN,367.88,166.89,141.86,25.04,Paid,NaN,Paper,NaN
1,CLM1033930,M102629,P2063,Professional,11 - Office,25-11-2025,25-11-2025,01-01-2026,09-02-2026,J02.9,NaN,388.26,151.58,151.58,0.00,Paid,NaN,Paper,NaN
2,CLM1046736,M103641,P2131,Professional,11 - Office,15-12-2025,15-12-2025,02-01-2026,07-02-2026,M25.561,NaN,580.47,239.80,239.80,0.00,Paid,NaN,Paper,NaN
3,CLM1002252,M100194,P2061,Professional,11 - Office,24-11-2025,24-11-2025,03-01-2026,05-02-2026,Z00.00,Z23,1061.48,747.23,726.13,21.10,Paid,NaN,Paper,NaN
4,CLM1060254,M104664,P2221,Professional,81 - Independent Lab,10-12-2025,10-12-2025,03-01-2026,14-02-2026,Z00.00,NaN,131.56,0.00,0.00,0.00,Denied,INF01,Paper,NaN

Column names:
['claim_id', 'mbr_id', 'provider_id', 'claim_type', 'place_of_service', 'svc_from_dt', 'svc_to_dt', 'received_date', 'processed_date', 'primary_diagnosis', 'secondary_diagnosis', 'total_billed', 'allowed_amt', 'paid_amt', 'member_responsibility', 'claim_status', 'denial_code', 'submission_channel', 'original_claim_id']

Data types:
claim_id                  object
mbr_id                    object
provider_id               object
claim_type                object
place_of_service          object
svc_from_dt               object
svc_to_dt                 object
received_date             object
processed_date            object
primary_diagnosis         object
secondary_diagnosis       object
total_billed             float64
allowed_amt              float64
paid_amt                 float64
member_responsibility    float64
claim_status              object
denial_code               object
submission_channel        object
original_claim_id         object
dtype: object

Missing values:
processed_date         1084
secondary_diagnosis    4929
denial_code            4916
original_claim_id      5223
dtype: int64

Duplicate rows: 0

File: claim_lines_2026_02.csv
Rows and columns: (9799, 9)

First 5 rows:

,claim_id,line_number,procedure_code,modifier,units,billed_amount,allowed_amount,paid_amount,line_status
0,CLM1000011,1,99214,NaN,1,697.33,204.80,204.80,Paid
1,CLM1000011,2,87804,NaN,1,63.95,26.51,26.51,Paid
2,CLM1000033,1,99213,NaN,1,442.57,276.50,248.84,Paid
3,CLM1000033,2,87804,NaN,1,81.09,47.54,42.79,Paid
4,CLM1000044,1,90834,NaN,1,427.37,310.00,279.00,Paid

Column names:
['claim_id', 'line_number', 'procedure_code', 'modifier', 'units', 'billed_amount', 'allowed_amount', 'paid_amount', 'line_status']

Data types:
claim_id           object
line_number         int64
procedure_code     object
modifier           object
units               int64
billed_amount     float64
allowed_amount    float64
paid_amount       float64
line_status        object
dtype: object

Missing values:
modifier    9127
dtype: int64

Duplicate rows: 0

File: premiums_2026_02.csv
Rows and columns: (6928, 5)

First 5 rows:

  member_id premium_month plan_id  premium_amount payment_status
0   M100001       2026-02   PLN03             420       Received
1   M100002       2026-02   PLN08             370       Received
2   M100003       2026-02   PLN06             720       Received
3   M100004       2026-02   PLN07             960       Received
4   M100006       2026-02   PLN02             400       Received

Column names:
['member_id', 'premium_month', 'plan_id', 'premium_amount', 'payment_status']

Data types:
member_id         object
premium_month     object
plan_id           object
premium_amount     int64
payment_status    object
dtype: object

Missing values:
Series([], dtype: int64)

Duplicate rows: 0

File: claim_lines_2026_02-checkpoint.csv
Rows and columns: (9799, 9)

First 5 rows:

,claim_id,line_number,procedure_code,modifier,units,billed_amount,allowed_amount,paid_amount,line_status
0,CLM1000011,1,99214,NaN,1,697.33,204.80,204.80,Paid
1,CLM1000011,2,87804,NaN,1,63.95,26.51,26.51,Paid
2,CLM1000033,1,99213,NaN,1,442.57,276.50,248.84,Paid
3,CLM1000033,2,87804,NaN,1,81.09,47.54,42.79,Paid
4,CLM1000044,1,90834,NaN,1,427.37,310.00,279.00,Paid

Column names:
['claim_id', 'line_number', 'procedure_code', 'modifier', 'units', 'billed_amount', 'allowed_amount', 'paid_amount', 'line_status']

Data types:
claim_id           object
line_number         int64
procedure_code     object
modifier           object
units               int64
billed_amount     float64
allowed_amount    float64
paid_amount       float64
line_status        object
dtype: object

Missing values:
modifier    9127
dtype: int64

Duplicate rows: 0

File: claims_header_2026_03.csv
Rows and columns: (4972, 20)

First 5 rows:

,claim_id,member_id,provider_id,claim_type,place_of_service,service_from_date,service_to_date,received_date,processed_date,primary_diagnosis,secondary_diagnosis,total_billed,total_allowed,total_paid,member_responsibility,claim_status,denial_code,submission_channel,original_claim_id,telehealth_flag
0,CLM1003176,M100265,P2047,Professional,11 - Office,2026-01-20,2026-01-20,2026-02-02,2026-03-07,I10,I10,567.71,308.07,261.87,46.20,Paid,NaN,Paper,NaN,N
1,CLM1026652,M102066,P2168,Professional,11 - Office,2026-01-19,2026-01-19,2026-02-02,2026-03-03,F41.1,NaN,516.08,316.43,253.13,63.29,Paid,NaN,Paper,NaN,N
2,CLM1074364,M105768,P2141,Professional,11 - Office,2026-01-19,2026-01-19,2026-02-02,2026-03-13,J10.1,NaN,524.04,322.67,225.87,96.80,Paid,NaN,Paper,NaN,N
3,CLM1096410,M107488,P2228,Institutional,23 - Emergency Room,2026-01-25,2026-01-25,2026-02-02,2026-03-20,R07.9,NaN,1751.62,1139.67,797.74,341.92,Paid,NaN,Paper,NaN,N
4,CLM1001262,M100105,P2055,Professional,11 - Office,2026-01-19,2026-01-19,2026-02-03,2026-03-10,J02.9,NaN,289.41,163.79,131.03,32.76,Paid,NaN,Paper,NaN,N

Column names:
['claim_id', 'member_id', 'provider_id', 'claim_type', 'place_of_service', 'service_from_date', 'service_to_date', 'received_date', 'processed_date', 'primary_diagnosis', 'secondary_diagnosis', 'total_billed', 'total_allowed', 'total_paid', 'member_responsibility', 'claim_status', 'denial_code', 'submission_channel', 'original_claim_id', 'telehealth_flag']

Data types:
claim_id                  object
member_id                 object
provider_id               object
claim_type                object
place_of_service          object
service_from_date         object
service_to_date           object
received_date             object
processed_date            object
primary_diagnosis         object
secondary_diagnosis       object
total_billed             float64
total_allowed            float64
total_paid               float64
member_responsibility    float64
claim_status              object
denial_code               object
submission_channel        object
original_claim_id         object
telehealth_flag           object
dtype: object

Missing values:
processed_date          872
secondary_diagnosis    4717
denial_code            4632
original_claim_id      4959
dtype: int64

Duplicate rows: 35

File: claim_lines_2026_03.csv
Rows and columns: (9052, 9)

First 5 rows:

,claim_id,line_number,procedure_code,modifier,units,billed_amount,allowed_amount,paid_amount,line_status
0,CLM1000030,1,71046,NaN,1,161.46,85.45,76.91,Paid
1,CLM1000047,1,90834,NaN,1,521.88,310.18,279.16,Paid
2,CLM1000048,1,90791,NaN,1,846.32,510.49,459.45,Paid
3,CLM1000049,1,90834,NaN,1,433.22,319.11,287.19,Paid
4,CLM1000075,1,99214,NaN,1,708.51,300.39,255.33,Paid

Column names:
['claim_id', 'line_number', 'procedure_code', 'modifier', 'units', 'billed_amount', 'allowed_amount', 'paid_amount', 'line_status']

Data types:
claim_id           object
line_number         int64
procedure_code     object
modifier           object
units               int64
billed_amount     float64
allowed_amount    float64
paid_amount       float64
line_status        object
dtype: object

Missing values:
modifier    8207
dtype: int64

Duplicate rows: 0

File: premiums_2026_03.csv
Rows and columns: (6928, 5)

First 5 rows:

  member_id premium_month plan_id  premium_amount payment_status
0   M100001       2026-03   PLN03             420       Received
1   M100002       2026-03   PLN08             370       Received
2   M100003       2026-03   PLN06             720       Received
3   M100004       2026-03   PLN07             960       Received
4   M100006       2026-03   PLN02             400       Received

Column names:
['member_id', 'premium_month', 'plan_id', 'premium_amount', 'payment_status']

Data types:
member_id         object
premium_month     object
plan_id           object
premium_amount     int64
payment_status    object
dtype: object

Missing values:
Series([], dtype: int64)

Duplicate rows: 0

File: claim_lines_2026_03-checkpoint.csv
Rows and columns: (9052, 9)

First 5 rows:

,claim_id,line_number,procedure_code,modifier,units,billed_amount,allowed_amount,paid_amount,line_status
0,CLM1000030,1,71046,NaN,1,161.46,85.45,76.91,Paid
1,CLM1000047,1,90834,NaN,1,521.88,310.18,279.16,Paid
2,CLM1000048,1,90791,NaN,1,846.32,510.49,459.45,Paid
3,CLM1000049,1,90834,NaN,1,433.22,319.11,287.19,Paid
4,CLM1000075,1,99214,NaN,1,708.51,300.39,255.33,Paid

Column names:
['claim_id', 'line_number', 'procedure_code', 'modifier', 'units', 'billed_amount', 'allowed_amount', 'paid_amount', 'line_status']

Data types:
claim_id           object
line_number         int64
procedure_code     object
modifier           object
units               int64
billed_amount     float64
allowed_amount    float64
paid_amount       float64
line_status        object
dtype: object

Missing values:
modifier    8207
dtype: int64

Duplicate rows: 0

In [21]:
for name, df in data.items():

# 1. Clean column names
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

 # 2. Clean text columns
    text_cols = df.select_dtypes(
        include=["object", "string"]
    ).columns

    for col in text_cols:
        df[col] = df[col].str.strip()
        df[col] = df[col].replace("", pd.NA)

 # 3. Remove exact duplicate rows
    before = len(df)

    df.drop_duplicates(inplace=True)

    removed = before - len(df)

    print(
        name,
        "| Rows after cleaning:", len(df),
        "| Duplicates removed:", removed
    )

claims_header_2026_01.csv | Rows after cleaning: 6404 | Duplicates removed: 0
claim_lines_2026_01.csv | Rows after cleaning: 12914 | Duplicates removed: 0
premiums_2026_01.csv | Rows after cleaning: 6928 | Duplicates removed: 0
premiums_2026_01-checkpoint.csv | Rows after cleaning: 6928 | Duplicates removed: 0
claims_header_2026_02.csv | Rows after cleaning: 5266 | Duplicates removed: 0
claim_lines_2026_02.csv | Rows after cleaning: 9799 | Duplicates removed: 0
premiums_2026_02.csv | Rows after cleaning: 6928 | Duplicates removed: 0
claim_lines_2026_02-checkpoint.csv | Rows after cleaning: 9799 | Duplicates removed: 0
claims_header_2026_03.csv | Rows after cleaning: 4937 | Duplicates removed: 35
claim_lines_2026_03.csv | Rows after cleaning: 9052 | Duplicates removed: 0
premiums_2026_03.csv | Rows after cleaning: 6928 | Duplicates removed: 0
claim_lines_2026_03-checkpoint.csv | Rows after cleaning: 9052 | Duplicates removed: 0

In [22]:
output_folder = base_folder / "cleaned_data"
output_folder.mkdir(exist_ok=True)

for name, df in data.items():

    output_file = output_folder / name.replace(
        ".csv", "_cleaned.csv"
    )

    df.to_csv(output_file, index=False)

    print("Saved:", output_file.name)

Saved: claims_header_2026_01_cleaned.csv
Saved: claim_lines_2026_01_cleaned.csv
Saved: premiums_2026_01_cleaned.csv
Saved: premiums_2026_01-checkpoint_cleaned.csv
Saved: claims_header_2026_02_cleaned.csv
Saved: claim_lines_2026_02_cleaned.csv
Saved: premiums_2026_02_cleaned.csv
Saved: claim_lines_2026_02-checkpoint_cleaned.csv
Saved: claims_header_2026_03_cleaned.csv
Saved: claim_lines_2026_03_cleaned.csv
Saved: premiums_2026_03_cleaned.csv
Saved: claim_lines_2026_03-checkpoint_cleaned.csv

In [23]:
for name, df in data.items():

    print("\nFile:", name)
    print("Final shape:", df.shape)
    print("Remaining duplicates:", df.duplicated().sum())

    missing = df.isnull().sum()
    print("Missing values:")
    print(missing[missing > 0])

File: claims_header_2026_01.csv
Final shape: (6404, 19)
Remaining duplicates: 0
Missing values:
processed_date         1061
secondary_diagnosis    5609
denial_code            6021
original_claim_id      6362
dtype: int64

File: claim_lines_2026_01.csv
Final shape: (12914, 9)
Remaining duplicates: 0
Missing values:
modifier    11936
dtype: int64

File: premiums_2026_01.csv
Final shape: (6928, 5)
Remaining duplicates: 0
Missing values:
Series([], dtype: int64)

File: premiums_2026_01-checkpoint.csv
Final shape: (6928, 5)
Remaining duplicates: 0
Missing values:
Series([], dtype: int64)

File: claims_header_2026_02.csv
Final shape: (5266, 19)
Remaining duplicates: 0
Missing values:
processed_date         1084
secondary_diagnosis    4929
denial_code            4916
original_claim_id      5223
dtype: int64

File: claim_lines_2026_02.csv
Final shape: (9799, 9)
Remaining duplicates: 0
Missing values:
modifier    9127
dtype: int64

File: premiums_2026_02.csv
Final shape: (6928, 5)
Remaining duplicates: 0
Missing values:
Series([], dtype: int64)

File: claim_lines_2026_02-checkpoint.csv
Final shape: (9799, 9)
Remaining duplicates: 0
Missing values:
modifier    9127
dtype: int64

File: claims_header_2026_03.csv
Final shape: (4937, 20)
Remaining duplicates: 0
Missing values:
processed_date          866
secondary_diagnosis    4687
denial_code            4598
original_claim_id      4924
dtype: int64

File: claim_lines_2026_03.csv
Final shape: (9052, 9)
Remaining duplicates: 0
Missing values:
modifier    8207
dtype: int64

File: premiums_2026_03.csv
Final shape: (6928, 5)
Remaining duplicates: 0
Missing values:
Series([], dtype: int64)

File: claim_lines_2026_03-checkpoint.csv
Final shape: (9052, 9)
Remaining duplicates: 0
Missing values:
modifier    8207
dtype: int64